function spline2coil( sfile,cwsfile )
%SPLINE2COIL(spline_file,winding_file) Creates a coils file.
% This function reads a spline file generated by COILOPT++ and a winding
% surface file and calculates an MGRID style coils file name coils.spline.
%
% Example usage
%      spline2coil('coil_spline_test.out','windsurf_test.nes');
%      coil_data=read_coils('coils.spline');
%
% Maintained by: Samuel Lazerson (lazerson@pppl.gov)
% Version:       1.0

spline=read_coilopt_spline(sfile);
if isempty(spline), return; end
fid = fopen(cwsfile,'r');
if fid < 0 
    disp(['Coil Winding Surface File Error: ' cwsfile]);
    return;
end
cwsdata=fscanf(fid,'%E',[4 inf]);
fclose(fid);
xm=cwsdata(1,:);
xn=cwsdata(2,:);
rbc=cwsdata(3,:);
zbs=cwsdata(4,:);
theta=0:2*pi/89:2*pi;
zeta=0:2*pi/89:2*pi;
r=squeeze(cfunct(theta,zeta,rbc',xm,xn));
z=squeeze(sfunct(theta,zeta,zbs',xm,xn));
u=theta/(2*pi);
v=zeta/(2*pi);
for i=1:length(zeta);
    x(:,i) = r(:,i).*cos(zeta(i)/spline.nfp);
    y(:,i) = r(:,i).*sin(zeta(i)/spline.nfp);
end

coil_data.periods = spline.nfp;
datatype='coil_data';
coil_data.vert=[];
for i=1:spline.ncoil
    coil_data.current_name{i} = ['MOD' num2str(i)];
    uvarr=fnplt(spline.sp{i});
    for np = 1:coil_data.periods
        x_coil=interp2(u,v,x,uvarr(2,:),uvarr(1,:),'spline');
        y_coil=interp2(u,v,y,uvarr(2,:),uvarr(1,:),'spline');
        z_coil=interp2(u,v,z,uvarr(2,:),uvarr(1,:),'spline');
        r_coil=sqrt(x_coil.*x_coil+y_coil.*y_coil);
        p_coil=atan2(y_coil,x_coil) + 2*pi*(np-1)./coil_data.periods;
        x_coil=r_coil.*cos(p_coil);
        y_coil=r_coil.*sin(p_coil);
        verts=[x_coil; y_coil; z_coil];
        verts(4,:) = spline.current(i);
        verts(4,end) = 0.0;
        verts(5,:) = i;
        coil_data.vert = [coil_data.vert verts];
        coil_data.current_name{i} = ['MOD' num2str(i)];
        x_coil=interp2(u,v,x,1-uvarr(2,:),1-uvarr(1,:),'spline');
        y_coil=interp2(u,v,y,1-uvarr(2,:),1-uvarr(1,:),'spline');
        z_coil=interp2(u,v,z,1-uvarr(2,:),1-uvarr(1,:),'spline');
        r_coil=sqrt(x_coil.*x_coil+y_coil.*y_coil);
        p_coil=atan2(y_coil,x_coil) + 2*pi*(np-1)./coil_data.periods;
        x_coil=r_coil.*cos(p_coil);
        y_coil=r_coil.*sin(p_coil);
        verts=[x_coil; y_coil; z_coil];
        verts(4,:) = spline.current(i);
        verts(4,end) = 0.0;
        verts(5,:) = i;
        coil_data.vert = [coil_data.vert verts];
    end
end
write_mgrid_coil(coil_data,'coils.spline');

end

